spring:
  application:
    name: mail-pash-service
  profiles:
    active: prod
  config:
    import: optional:configserver:http://172.18.0.6:8888
eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.5:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}